### ISSUE TITLE
make train function's plot optional through arguments

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/core-module#10]
It seems like the training might require this, or at the very least it will make things simpler. Also might not be a bad idea for other reasons as well to be able to turn off the plot feature and not force it on the user.

**Comment by mikkokotila** [comment]
The way to overcome this is:

```
import matplotlib
matplotlib.use('Agg')
```
Note how this has to be before:

`import matplotlit.pyplot as plt`

Otherwise it will not work. Now I have to still find out how this will behave if we run the same function in jupyter.

**Comment by mikkokotila** [comment]
Maybe it's best to include this in the verbose. We need to think how to do it as 'verbose' is also fed into Keras, so we have to consistency. I think the options are: 

- nothing at all
- just accuarcy 
- accuracy and parameters 
- accuracy, parameters and shape

For Keras there are 0,1,2 for verbosity. 

maybe plot should be separately true or false?

**Comment by konchokdolma** [comment]
You can now do this with train(x, y, data, hyperscan=True)
