### ISSUE TITLE
why are we passing 'flatten' in load model? 

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/core-module#120]
It seems that this is not needed, as load_model is only used for predictions, and predictions should never have 'y' which is what flatten is used with?

**Comment by konchokdolma** [comment]
Yes, indeed we do not need it for predictions. I will remove it.

**Comment by konchokdolma** [comment]
Done. Changes are in daily-dev

**Comment by mikkokotila** [comment]
Great thanks! :)
