### ISSUE TITLE
allow user to set the parameters for layer dimensions

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/core-module#122]
Let's allow a list input with integers so that hidden layer neuron count is possible to configure manually. So if I have 5 layers I might do [128,128,64,32,16] for some problem. This will be good, as now currently the user is stuck with the shapes we give.

**Comment by konchokdolma** [comment]
Done. Changes are for now in daily-dev. You can define neurons doing, for example: train(x, y, data, neurons = [4, 5, 6])

**Comment by mikkokotila** [comment]
This is really great, will try it out :)
