### ISSUE TITLE
PEP8 check github pull requests automatically

### ISSUE THREAD

**Issue by m-anish** [autonomio/core-module#15]
Following #8 , I was looking at tools in github that would help with this. To this end, I found a tool called pep8speaks (https://github.com/OrkoHunter/pep8speaks) which is a github integration. After every pull request is created, the integration scans through any python code as part of the commits, and runs a pep8 checker on it. After checking, a comment if posted to the pull request with all the PEP8 errors or warnings present.

You can see an example here.
https://github.com/m-anish/autonomio/pull/2#issuecomment-296527461

Should we try integrating it with our repo?

Once we are more stringent with coding practices, we can enforce a travis build failure if the code is not PEP8 compliant. You can see an example of that here:

https://travis-ci.org/m-anish/autonomio/builds/224940333

If you scroll through the log to the end, you will see all the PEP8 violations have been reported, and the build failed. This is a more stringent version of enforcing PEP8. But until we clear these exceptions (which I will), we can opt with this nice and suggestive integration.

**Comment by mikkokotila** [comment]
This looks perfect. I agree, let's implement this once we've thoroughly implemented testing (with output validation!) and have close to 100% code coverage.

**Comment by m-anish** [comment]
Okay, I am assigning this to myself to pull in this integration.

**Comment by m-anish** [comment]
Actually, I can't do this as I dont have admin rights on this repo. I will reassign this to you. Sorry for the extra noise.

**Comment by mikkokotila** [comment]
I've fixed the admin issue so now you should be ok :)

**Comment by mikkokotila** [comment]
Added this. Thanks! Will see about the Travis build part later. We already have master as protected branch where tests have to pass before can merge, and I'm assuming that this will fall under that even without Travis as it's own item.
