### ISSUE TITLE
User Experience Factors

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/core-module#16]
It seems to be a good time to discuss how we can have [commands()](https://github.com/botlabio/autonomio/blob/master/autonomio/commands.py) available through a user interface. For this we have to decide: 

1) which Javascript framework to adopt
2) which Javascript visualization package to adopt 

It seems that we can split this in to three parts: 

- frontend build and connect to API hooks
- setting up the hooks to support both ends
- providing at the backend what frontend demands 

I will work on a mock of how the UI would look like together with spec now. It's pretty straightforward as we will simply replicate the functionality of the three commands in [commands()](https://github.com/botlabio/autonomio/blob/master/autonomio/commands.py).

**Comment by mikkokotila** [comment]
This is pretty interesting and well worth related with the topic: 

https://hackernoon.com/javascript-what-excites-me-in-2017-7681766b7d79

**Comment by mikkokotila** [comment]
Here is a guideline we wrote a few years back as a guideline to building analytical dashboards. 

[An Evidence Based Approach to Analytics Dashboads.pdf](https://github.com/botlabio/autonomio/files/950687/An.Evidence.Based.Approach.to.Analytics.Dashboads.pdf)

**Comment by mikkokotila** [comment]
[Detail Admin](http://wrapbootstrap.com/preview/WB07061TJ)
[Controlfrog](http://wrapbootstrap.com/preview/WB025R2B9)
[Nucleus](http://nucleus.amazyne.com/v2/tables-datatables.html)

**Comment by mikkokotila** [comment]
Rui just recommended this: https://www.typescriptlang.org/

**Comment by mikkokotila** [comment]
<img width="1263" alt="screen shot 2017-04-24 at 14 19 08" src="https://cloud.githubusercontent.com/assets/7943188/25334829/09f48c6a-28f9-11e7-8e3c-1109c2dd65f4.png">
<img width="1263" alt="screen shot 2017-04-24 at 14 19 53" src="https://cloud.githubusercontent.com/assets/7943188/25334847/1b03c552-28f9-11e7-97d2-70d9999a4f55.png">

**Comment by mikkokotila** [comment]
That's what I was able to work out so far :)

**Comment by m-anish** [comment]
@mikkokotila I was having a discussion with Prasenjit on this. Here are a few things he said.

1. He said that he will look at and/or fork this repo and look at our issue tracker.
2. Off the bat, he recommended that a initial webapp could be built just using d3 and basic js boilerplate stuff (like bootstrap perhaps). 
3. If we want a python frontend, he said there is tornadoweb which could be looked into http://www.tornadoweb.org/en/stable/
4. He said if we want to have hosted demos where users can mix and match things, it might be best to have the datasets pre-stored on the server, so the user isn't uploading the dataset during a simulation, otherwise it might involve high bandwidth costs. 
5. He agreed with the idea of a core repo and wrapper repos. So one repo providing core functionality, and one providing perhaps jupyter, and one perhaps a web-frontend or something of that sort.
6. He also thought that using webhooks to communicate between the core and webapp is a good idea.

**Comment by mikkokotila** [comment]
<img width="316" alt="screen shot 2017-04-24 at 14 47 36" src="https://cloud.githubusercontent.com/assets/7943188/25335784/287f5c60-28fd-11e7-89ec-8aeb8c88eb6b.png">

This is related with point (4) from above. I think initially we can focus on making the docker available so we can focus on making sure the user can ingest data "normally" even though they are behind a GUI. These 6 seem to cover it and pretty easy to implement on the backend. We can get most from pandas, and twitter to pandas dataframe with some custom metrics like sentiment I have ready.

**Comment by mikkokotila** [comment]
This will take more work to have it looking good, but the functionality is now all there. For the x and y boxes we will have a mechanism that allows selecting one, multiple, 'select all'.

![screen shot 2017-04-24 at 21 27 26](https://cloud.githubusercontent.com/assets/7943188/25352505/e3521988-2934-11e7-9db2-e7faec1c6e0c.png)

**Comment by mikkokotila** [comment]
This is progressing well. This is now created dynamically after uploading a csv. Seems like the simplest way is to just make post request with PHP, pass all the inputs as sys args (we can always pass default values so it's a fixed number of inputs every time) and then we use matplotlib to produce image for the plot, bootstrap for html/css and a very simple custom html templating engine that puts it all together neatly. 

![screen shot 2017-04-25 at 22 46 56](https://cloud.githubusercontent.com/assets/7943188/25404577/3779ff38-2a09-11e7-84f7-02edab96227f.png)

**Comment by mikkokotila** [comment]
The setup view starts to be ready to connect as well...

![screen shot 2017-04-26 at 10 55 14](https://cloud.githubusercontent.com/assets/7943188/25423897/fa92e4f2-2a6e-11e7-88a0-0f7288a44fea.png)

**Comment by mikkokotila** [comment]
</div></div></div></div></div></div></div></div></div>

...apparently that's an actual thing.

**Comment by mikkokotila** [comment]
"</div></div></div></div></div></div></div></div></div>"

**Comment by mikkokotila** [comment]
Great news, it seems like the pipeline is now stitched together from back to front. Will work on tidying everything up now.

**Comment by m-anish** [comment]
Awesome work!

**Comment by m-anish** [comment]
I guess this is pending on your creating the new repo. Removing myself as an assignee

**Comment by mikkokotila** [comment]
As this is related with the GUI, closing it now.
