### ISSUE TITLE
Creating Docker Container 

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/core-module#19]
As it seems we're all in agreement that docker container is the way to go, I'm creating this issue so we can go ahead with it.

I think the first thing is to create a Dockerfile based on the setup script and make sure that it past > troubleshoot accordingly. Timing is very good as tomorrow or day after tomorrow I should have a rough version of the frontend ready so we can plug that in.

**Comment by mikkokotila** [comment]
It looks like that the container will shutdown on your machine after you start it. Here is an instruction to overcome it: http://stackoverflow.com/questions/30209776/docker-container-will-automatically-stop-after-docker-run-d

**Comment by mikkokotila** [comment]
This is now a result from inside the container. All we have to is have the image restart apache (I've edited the docker file). I should have all the codes up for the UI tomorrow.

![screen shot 2017-04-27 at 18 26 59](https://cloud.githubusercontent.com/assets/7943188/25490962/294f045c-2b77-11e7-8cf1-747c1d334b6e.png)

**Comment by mikkokotila** [comment]
This is now more or less done. I did not test with the latest version yet where only change a tested apache restart command. 

[get what goes in to the docker container here](https://github.com/botlabio/autonomio/tree/master/non-core)

You can find all the files with my development branch of the core. Actually only one very small bug is fixed and the plotting is arranged in a way where I'm not yet sure if it will work with jupyter or not. For tomorrow the plan is to work out how we can have the GUI and then as one link in it Jupyter so you can turn on "advanced mode" anytime you. I think maybe we could even make it look a little similar and then just say "powered by iPython". 

But yes after big struggle between two people this is now in good standing! :)

**Comment by mikkokotila** [comment]
[UPDATED docker buildin'](
https://github.com/botlabio/autonomio/blob/master/non-core/docker_inside.zip)

Ok guys, yesterday two man on skype for 5 hours and throw in another 10 hours, and it's starting to look pretty good. Jupyter is in also! :) This is big as it means I can just move to using the container version 100% myself too.

**Comment by m-anish** [comment]
This is dependent on @mikkokotila checking in the docker stuff into a repo. Removing myself as assignee till then :)

**Comment by mikkokotila** [comment]
Aha, now you're back ;)

**Comment by mikkokotila** [comment]
Thanks a lot for all the hard work that went in to this. At some point, when the time is right for a focus on GUI  / non-programmer implementation, this will be very useful :) Closing now.
