### ISSUE TITLE
separating core, container and visuals to separate repos

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/core-module#27]
It seems that visualization, container and core are all separate use-cases and seems to make sense to separate. This way we could for example make sure the plots work for Keras and TensorFlow users as well. It seems like basic (bubble etc) charts that look fantastic are entirely missing from deep learning. 

I already spent a few months with the visualization aspect to build [Astetik](https://github.com/mikkokotila/astetik) so we could just fork that as the base and add the plots we already have, and remove the ones that are not relevant. 

There might be one more, which is a data transformation module as we are already doing it a lot and it makes the core code confusing. Again, having a data transformation library available for non-Autonomio users could be very valuable for Keras/TensorFlow users. 

So that would make 4 separate packages: 

- core
- visualize
- transform
- container (everything is included)

**Comment by m-anish** [comment]
I agree. 

The repo is being bloated a bit and we need to check that going forward.
https://github.com/botlabio/autonomio/commit/a40c33f041a5751c1338ebe0c2cc5934c73466ff

**Comment by mikkokotila** [comment]
Ok great and I agree it's super bloated. So this is the plan: 

1) Clean the current repo 
2) Update the current master with my "branch"
3) Take the files unique to docker to its own repo
4) Modify the docker file so that it gets autonomio-core from master
5) Create Travis and code coverage tests for autonomio-full 
6) Create pypi package for both autonomio-core and autonomio-full

Then after that I can work on separating visualization and once that is done, separating all data transformation. The good news is that I already did all the work for this guessing that it would have to be looked at later :) The work involved in separating the data transformation is minimal and with plots maybe 2-3 days. 

We also have to get the data out from the core package as its tens of mb.

**Comment by mikkokotila** [comment]
This seems to also imply that we move this in to an org of its own. If we do that, would the right way to be to just move the repo from one org to other? It'll be too confusing to have all that under one org. Also if we like under org we can do things like autonomio/core and autonomio/full.

**Comment by m-anish** [comment]
I think it is fine to have things under one org.

**Comment by mikkokotila** [comment]
Almost there...waiting for travis to go through and will invite then (as you will have to include the core module with whatever is there given we don't still have pypi package...what do you think, should we do git install from master with pip as part of Dockerfile? ... well I'll open this in the new repo as an issue.

**Comment by mikkokotila** [comment]
Travis passed. We have a new repo and I guess still during today I can have everything moved there (including this current repo).

**Comment by m-anish** [comment]
Great. On that repo too, can you add the slack channel integration. :)

**Comment by mikkokotila** [comment]
Ok done :)

**Comment by mikkokotila** [comment]
This is now all done. Waiting for Travis to run for the first time :)
