### ISSUE TITLE
Changing random seed in the core function

### ISSUE THREAD

**Issue by amitphan** [autonomio/core-module#28]
The random seed seems to be currently fixed in the core function. Can this be changed to a true random seed with an input parameter to train function where a user can fix it if needed.

**Comment by mikkokotila** [comment]
If I understand correct, at the moment there is nowhere we are using it as we don't in our own code invoke any random function from numpy. Did I understand correct?

**Comment by amitphan** [comment]
We invoke the np random seed function in our code. We want to see if that can be fixed to say random seed(20), so that a user can test and get the exact same results everytime

**Comment by mikkokotila** [comment]
I think we better add this to the parameters for 'train' so that by default it is not static, but if you want to reproduce the same result, then you invoke it. So we could just have 'false' by default, and then 'True' to invoke it. Or maybe use int, as it's faster to type ;)

**Comment by mikkokotila** [comment]
Actually having tried this in a loop, it does not do anything i.e. regardless of changing the value, or not having it, the variation in results is roughly the same (in my case between 77% and 82%). Closing this.
