### ISSUE TITLE
Autonomio Roadmap

### ISSUE THREAD

**Issue by yaroslavvb** [autonomio/core-module#31]
This project looks really cool!
Sorry for filing an issue, I couldn't find any emails on the web, is it possibly to get more info on the roadmap, and if you are planning to let other people contribute?

**Comment by mikkokotila** [comment]
Thanks a lot for opening :) 

I'm very sorry for the delayed response. We do have a pretty clear high-level roadmap and on Friday I started to make it in to a format where I could post it as blogpost. Then I went out to "bicycle in the sun" and ended up with a concussion after wiping out pretty badly head first. CT scan nothing is broken, so just takes time to recover. I think walking is better for researchers in any case :p

Today I should be able to do some small things around here, and will prioritize posting the roadmap and sharing the link before anything else. Tried on Saturday but felt like "cache was flooding" so stopped. 

Regarding contributors, I think your profile looks fantastic so we would gladly welcome you with open arms. Thanks a lot for already helping on the Travis version / Tensorflow issue.

**Comment by mikkokotila** [comment]
I've added it now in our blog > [Autonomio Blog | Autonomio Roadmap](http://autonom.io/autonomio-roadmap/). 

This is very high level, and I'm happy to provide more details on any individual item. I'm changing the issue name to "Roadmap" so we could have this conversation here on-going in a transparent manner.

**Comment by mikkokotila** [comment]
Here is a link to [contributing guidelines](https://github.com/autonomio/core-module/blob/master/CONTRIBUTING.md).
