### ISSUE TITLE
Programming guideline: Use python logging instead of print

### ISSUE THREAD

**Issue by m-anish** [autonomio/core-module#6]
Use python's inbuilt logging library instead of print statements for more logically structured IO

Reference: https://docs.python.org/2/library/logging.html

**Comment by m-anish** [comment]
I guess this is pending a future implementation. I am assigning it to myself.

**Comment by mikkokotila** [comment]
Closing this for now. We moved to string formatting type print statements, and also almost entirely removed prints. I think we can remove prints entirely at some point.
