### ISSUE TITLE
streamline the way commands / parameters are added

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/core-module#62]
Let's significantly streamline the way parameters are added to commands that are already there, and how new commands are added. I think the most important criteria is:  

**in addition to the related function file, only commands should have to be edited**

**Comment by konchokdolma** [comment]
If you want to add new command, you should:
1. Create new file for the command
2. Identify all the parameters you want to pass
3. Add a new function into the commands
4. Create a dictionary with the needed parameters
